import type { Job } from '@/models/Job';
import { JobStatus } from '@/models/Job';

// 50 sample job postings for major Vietnamese hospitals and medical institutions
export const jobs: Job[] = [
  {
    _id: 'job_001',
    id: 'job_001',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    title: 'Bác sĩ Nội khoa (Hạ tầng tim mạch)',
    description:
      'Khám và điều trị các bệnh nội khoa liên quan đến tim mạch, thực hiện hội chẩn và quản lý bệnh nhân cấp cứu.',
    status: JobStatus.OPEN,
    location: 'Bệnh viện Bạch Mai, Hà Nội',
    company: 'Bệnh viện Bạch Mai',
    salaryRange: [15000000, 40000000],
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 60),
    requirements: [
      'Bằng bác sĩ chuyên khoa nội',
      'Kinh nghiệm 3+ năm tại khoa tim mạch',
      'Ưu tiên có chứng chỉ tim mạch can thiệp',
    ],
    benefits: ['BHYT, chế độ phúc lợi nhân viên', 'Đào tạo chuyên môn thường xuyên'],
    contactEmail: 'tuyendung@bachmai.org.vn',
    applyLink: 'https://bachmai.vn/tuyen-dung',
  },
  {
    _id: 'job_002',
    id: 'job_002',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    title: 'Bác sĩ Sản - Phụ khoa',
    description: 'Thực hiện khám, chăm sóc thai sản, phẫu thuật sản phụ khoa, tham gia trực chuyên môn.',
    status: JobStatus.OPEN,
    location: 'Bệnh viện Phụ Sản Trung ương, Hà Nội',
    company: 'Bệnh viện Phụ Sản Trung ương',
    salaryRange: [12000000, 35000000],
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 45),
    requirements: ['Bác sĩ chuyên khoa Sản', 'Kỹ năng phẫu thuật tốt', 'Thành thạo siêu âm thai'],
    benefits: ['Hỗ trợ học tập, BHYT', 'Tham gia nhóm nghiên cứu khoa học'],
    contactEmail: 'hr@pstw.vn',
    applyLink: 'https://ps.tw.vn/tuyen-dung',
  },
  {
    _id: 'job_003',
    id: 'job_003',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    title: 'Bác sĩ Ngoại tổng quát',
    description: 'Thực hiện phẫu thuật ngoại tổng quát, chăm sóc hậu phẫu và tham gia đào tạo sinh viên.',
    status: JobStatus.OPEN,
    location: 'Bệnh viện Việt Đức, Hà Nội',
    company: 'Bệnh viện Việt Đức',
    salaryRange: [18000000, 45000000],
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 30),
    requirements: ['Bác sĩ chuyên khoa Ngoại', 'Kinh nghiệm phẫu thuật 5+ năm', 'Kỹ năng lãnh đạo kíp mổ'],
    benefits: ['Chế độ nhà ở công vụ (theo chính sách)', 'Cơ hội hợp tác quốc tế'],
    contactEmail: 'tuyendung@vietduc.org.vn',
    applyLink: 'https://vietduc.org.vn/jobs',
  },
  {
    _id: 'job_004',
    id: 'job_004',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    title: 'Điều dưỡng Hồi sức cấp cứu',
    description: 'Chăm sóc người bệnh tại khoa Hồi sức cấp cứu, vận hành thiết bị y tế hỗ trợ điều trị.',
    status: JobStatus.OPEN,
    location: 'Bệnh viện Chợ Rẫy, TP. HCM',
    company: 'Bệnh viện Chợ Rẫy',
    salaryRange: [8000000, 18000000],
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 20),
    requirements: ['Cử nhân Điều dưỡng', 'Ưu tiên có chứng chỉ ICU/CCU'],
    benefits: ['Đóng BHXH/BHYT', 'Chương trình đào tạo nội bộ'],
    contactEmail: 'nhansu@choray.vn',
  },
  {
    _id: 'job_005',
    id: 'job_005',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    title: 'Bác sĩ Tai - Mũi - Họng',
    description: 'Khám và phẫu thuật các bệnh lý tai mũi họng, tham gia khám sâu và điều trị ngoại trú.',
    status: JobStatus.OPEN,
    location: 'Bệnh viện Tai Mũi Họng Trung ương, Hà Nội',
    company: 'Bệnh viện Tai Mũi Họng Trung ương',
    salaryRange: [10000000, 30000000],
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 50),
    requirements: ['Bác sĩ chuyên khoa Tai Mũi Họng', 'Kinh nghiệm phẫu thuật nội soi'],
    benefits: ['Hỗ trợ nghiên cứu', 'Chế độ lương theo năng lực'],
    contactEmail: 'recruit@tmh.tw.vn',
  },

  // Generated programmatically-like entries to reach 50 items but written out for clarity

  {
    _id: 'job_006',
    id: 'job_006',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    title: 'Bác sĩ Chẩn đoán hình ảnh',
    description: 'Thực hiện và đọc các hình ảnh X-quang, CT, MRI; tham gia hội chẩn chuyên khoa.',
    status: JobStatus.OPEN,
    location: 'Bệnh viện Đại học Y Hà Nội, Hà Nội',
    company: 'Đại học Y Hà Nội - Bệnh viện',
    salaryRange: [14000000, 32000000],
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 40),
    requirements: ['Bác sĩ chuyên khoa Chẩn đoán hình ảnh', 'Thành thạo đọc MRI/CT'],
    benefits: ['Cơ hội nghiên cứu cùng giảng viên ĐHY', 'Hỗ trợ học tập sau đại học'],
    contactEmail: 'jobs@hmu.edu.vn',
  },
  {
    _id: 'job_007',
    id: 'job_007',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    title: 'Bác sĩ Gây mê Hồi sức',
    description: 'Gây mê trong phẫu thuật lớn, quản lý đau và hồi sức sau mổ.',
    status: JobStatus.OPEN,
    location: 'Bệnh viện Việt - Pháp, Hà Nội',
    company: 'Bệnh viện Việt - Pháp',
    salaryRange: [20000000, 50000000],
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 35),
    requirements: ['Chuyên khoa Gây mê hồi sức', 'Kinh nghiệm bệnh viện tư quốc tế là lợi thế'],
    benefits: ['Môi trường quốc tế', 'Lương cạnh tranh và thưởng hiệu suất'],
    contactEmail: 'hr@vfmc.vn',
  },
  {
    _id: 'job_008',
    id: 'job_008',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    title: 'Bác sĩ Nhi khoa',
    description: 'Khám và điều trị bệnh nhi, tham gia tiêm chủng và tư vấn dinh dưỡng.',
    status: JobStatus.OPEN,
    location: 'Bệnh viện Nhi Trung ương, Hà Nội',
    company: 'Bệnh viện Nhi Trung ương',
    salaryRange: [12000000, 30000000],
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 60),
    requirements: ['Bác sĩ chuyên khoa Nhi', 'Kỹ năng giao tiếp với trẻ và phụ huynh'],
    benefits: ['Đào tạo chuyên môn', 'BHYT đầy đủ'],
    contactEmail: 'tuyendung@nhi.vn',
  },
  {
    _id: 'job_009',
    id: 'job_009',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    title: 'Dược sĩ Lâm sàng',
    description: 'Tư vấn sử dụng thuốc cho bệnh nhân, phối hợp với các khoa lâm sàng.',
    status: JobStatus.OPEN,
    location: 'Bệnh viện Trung ương Huế',
    company: 'Bệnh viện Trung ương Huế',
    salaryRange: [9000000, 20000000],
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 25),
    requirements: ['Cử nhân Dược', 'Kinh nghiệm làm việc tại bệnh viện'],
    benefits: ['Chế độ BHXH, BHYT', 'Tham gia nghiên cứu lâm sàng'],
    contactEmail: 'phongnhansu@huehosp.vn',
  },
  {
    _id: 'job_010',
    id: 'job_010',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    title: 'Kỹ thuật viên Xét nghiệm',
    description: 'Thực hiện các xét nghiệm huyết học, sinh hóa và vi sinh.',
    status: JobStatus.OPEN,
    location: 'Bệnh viện Đa khoa TPHCM',
    company: 'Bệnh viện Đa khoa TPHCM',
    salaryRange: [7000000, 15000000],
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 30),
    requirements: ['Cao đẳng/Đại học Xét nghiệm y học', 'Kỹ năng kiểm soát chất lượng xét nghiệm'],
    benefits: ['Đào tạo kỹ thuật mới', 'Chế độ bảo hiểm đầy đủ'],
    contactEmail: 'recruit@tphcmhosp.vn',
  },

  // jobs 11-50: mix of roles across major hospitals

  {
    _id: 'job_011',
    id: 'job_011',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    title: 'Bác sĩ Da liễu',
    description: 'Khám và điều trị các bệnh lý da liễu, thực hiện thủ thuật laser và thẩm mỹ da cơ bản.',
    status: JobStatus.OPEN,
    location: 'Bệnh viện Da liễu Trung ương, Hà Nội',
    company: 'Bệnh viện Da liễu Trung ương',
    salaryRange: [10000000, 26000000],
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 40),
    requirements: ['Chuyên khoa Da liễu', 'Kỹ năng thủ thuật thẩm mỹ là lợi thế'],
    benefits: ['Hỗ trợ tham gia hội thảo', 'BHYT'],
    contactEmail: 'hr@derm.tw.vn',
  },
  {
    _id: 'job_012',
    id: 'job_012',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    title: 'Bác sĩ Ung bướu',
    description: 'Khám, điều trị ung thư bằng hóa trị, phối hợp đa chuyên khoa.',
    status: JobStatus.OPEN,
    location: 'Bệnh viện K, Hà Nội',
    company: 'Bệnh viện K',
    salaryRange: [15000000, 38000000],
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 55),
    requirements: ['Chuyên khoa Ung bướu', 'Kinh nghiệm điều trị hóa trị'],
    benefits: ['Cơ hội nghiên cứu lâm sàng', 'Hỗ trợ học thuật'],
    contactEmail: 'recruit@benhvienk.vn',
  },
  {
    _id: 'job_013',
    id: 'job_013',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    title: 'Bác sĩ Tim mạch can thiệp',
    description: 'Thực hiện can thiệp tim mạch, đặt stent và xử lý các trường hợp cấp cứu.',
    status: JobStatus.OPEN,
    location: 'Bệnh viện Tim Hà Nội',
    company: 'Bệnh viện Tim Hà Nội',
    salaryRange: [25000000, 70000000],
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 20),
    requirements: ['Chuyên ngành Can thiệp Tim mạch', 'Kinh nghiệm can thiệp 3+ năm'],
    benefits: ['Thưởng case thành công', 'Chế độ bảo hiểm cao cấp'],
    contactEmail: 'hr@timhanoi.vn',
  },
  {
    _id: 'job_014',
    id: 'job_014',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    title: 'Bác sĩ Phẫu thuật thần kinh',
    description: 'Thực hiện phẫu thuật thần kinh, chăm sóc bệnh nhân trước và sau mổ.',
    status: JobStatus.OPEN,
    location: 'Bệnh viện Việt Đức, Hà Nội',
    company: 'Bệnh viện Việt Đức',
    salaryRange: [30000000, 80000000],
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 60),
    requirements: ['Phẫu thuật thần kinh chuyên sâu', 'Kinh nghiệm phẫu thuật lớn'],
    benefits: ['Hỗ trợ nghiên cứu và hợp tác quốc tế'],
    contactEmail: 'neurosurgery@vietduc.org',
  },
  {
    _id: 'job_015',
    id: 'job_015',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    title: 'Chuyên gia dinh dưỡng lâm sàng',
    description: 'Tư vấn dinh dưỡng cho bệnh nhân nội trú và ngoại trú, phối hợp điều trị đa chuyên khoa.',
    status: JobStatus.OPEN,
    location: 'Bệnh viện Đại học Y Dược TP.HCM',
    company: 'Đại học Y Dược TP.HCM - Bệnh viện',
    salaryRange: [9000000, 22000000],
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 30),
    requirements: ['Cử nhân/Thạc sĩ Dinh dưỡng', 'Kinh nghiệm bệnh viện là lợi thế'],
    benefits: ['Đào tạo liên tục', 'Hỗ trợ nghiên cứu sinh'],
    contactEmail: 'nutrition@hcmc.edu.vn',
  },
  {
    _id: 'job_016',
    id: 'job_016',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    title: 'Bác sĩ Y học cổ truyền',
    description: 'Chẩn trị và phối hợp điều trị Y học cổ truyền cho bệnh nhân mãn tính và đau nhức.',
    status: JobStatus.OPEN,
    location: 'Bệnh viện Y học cổ truyền Trung ương',
    company: 'Bệnh viện Y học cổ truyền Trung ương',
    salaryRange: [8000000, 18000000],
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 45),
    requirements: ['Bác sĩ Y học cổ truyền', 'Kinh nghiệm châm cứu, bấm huyệt'],
    benefits: ['Chế độ điều dưỡng', 'Đào tạo chuyên môn'],
    contactEmail: 'recruit@ytc.tw.vn',
  },
  {
    _id: 'job_017',
    id: 'job_017',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    title: 'Bác sĩ Mắt',
    description: 'Khám và phẫu thuật các bệnh lý mắt, phẫu thuật đục thủy tinh thể và phẫu thuật bằng laser.',
    status: JobStatus.OPEN,
    location: 'Bệnh viện Mắt Trung ương, Hà Nội',
    company: 'Bệnh viện Mắt Trung ương',
    salaryRange: [12000000, 30000000],
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 30),
    requirements: ['Chuyên khoa Mắt', 'Kinh nghiệm phẫu thuật đục thủy tinh thể'],
    benefits: ['Cơ hội tham gia chương trình hợp tác quốc tế'],
    contactEmail: 'hr@eye.vn',
  },
  {
    _id: 'job_018',
    id: 'job_018',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    title: 'Bác sĩ Tâm thần',
    description: 'Khám và điều trị các rối loạn tâm thần, tham gia tư vấn và chương trình cộng đồng.',
    status: JobStatus.OPEN,
    location: 'Bệnh viện Tâm thần Trung ương I',
    company: 'Bệnh viện Tâm thần Trung ương I',
    salaryRange: [10000000, 25000000],
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 50),
    requirements: ['Chuyên khoa Tâm thần', 'Kinh nghiệm khám ngoại trú và nội trú'],
    benefits: ['Hỗ trợ đào tạo chuyên sâu', 'Chế độ BH'],
    contactEmail: 'info@mental1.vn',
  },
  {
    _id: 'job_019',
    id: 'job_019',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    title: 'Kỹ thuật viên Chẩn đoán hình ảnh (CT/MRI)',
    description: 'Vận hành máy CT, MRI, bảo đảm chất lượng hình ảnh và an toàn bức xạ.',
    status: JobStatus.OPEN,
    location: 'Bệnh viện 115, TP. HCM',
    company: 'Bệnh viện Quân y 175',
    salaryRange: [9000000, 18000000],
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 60),
    requirements: ['KTV chẩn đoán hình ảnh', 'Kỹ năng bảo trì cơ bản máy móc'],
    benefits: ['Đào tạo kỹ thuật cao', 'BHYT/BHXH'],
    contactEmail: 'hr@175.vn',
  },
  {
    _id: 'job_020',
    id: 'job_020',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    title: 'Bác sĩ Cấp cứu',
    description: 'Làm việc tại khoa Cấp cứu, xử lý bệnh nhân chấn thương, ngộ độc và cấp cứu nội khoa.',
    status: JobStatus.OPEN,
    location: 'Bệnh viện Việt Nam - Thụy Điển Uông Bí',
    company: 'Bệnh viện Việt Nam - Thụy Điển Uông Bí',
    salaryRange: [14000000, 33000000],
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 40),
    requirements: ['Chuyên khoa Cấp cứu', 'Kỹ năng ACLS/PALS'],
    benefits: ['Hỗ trợ đào tạo cấp cứu quốc tế', 'BHYT'],
    contactEmail: 'tuyendung@vmsquangbi.vn',
  },

  {
    _id: 'job_021',
    id: 'job_021',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    title: 'Bác sĩ Răng Hàm Mặt',
    description: 'Khám và phẫu thuật các bệnh lý RHM, phục hồi thẩm mỹ và nha khoa tổng quát.',
    status: JobStatus.OPEN,
    location: 'Bệnh viện Răng Hàm Mặt Trung ương Hà Nội',
    company: 'Bệnh viện RHM Trung ương',
    salaryRange: [10000000, 26000000],
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 28),
    requirements: ['Chuyên khoa RHM', 'Kinh nghiệm điều trị & phẫu thuật'],
    benefits: ['Cơ hội nghiên cứu', 'BHYT'],
    contactEmail: 'hr@rhm.vn',
  },
  {
    _id: 'job_022',
    id: 'job_022',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    title: 'Bác sĩ Vật lý trị liệu',
    description: 'Tư vấn và điều trị vật lý trị liệu cho bệnh nhân phục hồi chức năng.',
    status: JobStatus.OPEN,
    location: 'Bệnh viện Phục hồi chức năng Trung ương',
    company: 'Bệnh viện Phục hồi chức năng Trung ương',
    salaryRange: [8000000, 18000000],
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 35),
    requirements: ['Cử nhân/Đại học Vật lý trị liệu', 'Kinh nghiệm phục hồi chức năng'],
    benefits: ['Đào tạo chuyên sâu', 'Chế độ bảo hiểm đầy đủ'],
    contactEmail: 'hr@rehab.vn',
  },
  {
    _id: 'job_023',
    id: 'job_023',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    title: 'Bác sĩ Lao và Bệnh phổi',
    description: 'Khám và điều trị bệnh lao, phối hợp các chương trình phòng chống lao quốc gia.',
    status: JobStatus.OPEN,
    location: 'Viện Phổi Trung ương',
    company: 'Viện Phổi Trung ương',
    salaryRange: [9000000, 20000000],
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 40),
    requirements: ['Chuyên khoa Lao - Phổi', 'Kinh nghiệm điều trị lao kháng thuốc là một lợi thế'],
    benefits: ['Tham gia chương trình quốc tế', 'BHYT'],
    contactEmail: 'recruit@lunginstitute.vn',
  },
  {
    _id: 'job_024',
    id: 'job_024',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    title: 'Bác sĩ Nội soi Tiêu hóa',
    description: 'Thực hiện nội soi tiêu hóa trên và dưới, sinh thiết và can thiệp cơ bản.',
    status: JobStatus.OPEN,
    location: 'Bệnh viện Đa khoa TW Quảng Nam',
    company: 'Bệnh viện TW Quảng Nam',
    salaryRange: [13000000, 30000000],
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 45),
    requirements: ['Chuyên khoa Tiêu hóa', 'Thành thạo nội soi chẩn đoán và can thiệp nhẹ'],
    benefits: ['Chế độ lương theo năng lực', 'Hỗ trợ chuyển giao kỹ thuật'],
    contactEmail: 'tuyendung@qnhosp.vn',
  },
  {
    _id: 'job_025',
    id: 'job_025',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    title: 'Bác sĩ Y tế công cộng',
    description: 'Tham gia chương trình tiêm chủng, giám sát dịch tễ và hoạt động phòng chống dịch.',
    status: JobStatus.OPEN,
    location: 'Sở Y tế TP. Hà Nội',
    company: 'Sở Y tế Hà Nội',
    salaryRange: [9000000, 20000000],
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 60),
    requirements: ['Bác sĩ Y tế công cộng', 'Kinh nghiệm quản lý chương trình y tế'],
    benefits: ['Lương chính sách nhà nước', 'Chế độ nghỉ phép theo luật'],
    contactEmail: 'hr@hanoihealth.gov.vn',
  },

  {
    _id: 'job_026',
    id: 'job_026',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    title: 'Bác sĩ Phục hồi chức năng thần kinh',
    description: 'Điều trị phục hồi sau đột quỵ và chấn thương tủy sống, xây dựng phác đồ phục hồi.',
    status: JobStatus.OPEN,
    location: 'Bệnh viện Chấn thương Chỉnh hình, Hà Nội',
    company: 'Bệnh viện Chấn thương Chỉnh hình Trung ương',
    salaryRange: [10000000, 24000000],
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 30),
    requirements: ['Chuyên ngành Phục hồi chức năng', 'Kinh nghiệm điều trị sau đột quỵ'],
    benefits: ['Đào tạo chuyên môn liên tục', 'BHYT/BHXH'],
    contactEmail: 'recruit@ortho.vn',
  },
  {
    _id: 'job_027',
    id: 'job_027',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    title: 'Bác sĩ Nội tiết - Đái tháo đường',
    description: 'Khám và quản lý bệnh nhân đái tháo đường, thực hiện can thiệp chuyên sâu.',
    status: JobStatus.OPEN,
    location: 'Bệnh viện Nội tiết Trung ương',
    company: 'Bệnh viện Nội tiết Trung ương',
    salaryRange: [12000000, 28000000],
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 50),
    requirements: ['Chuyên khoa Nội tiết', 'Kinh nghiệm quản lý bệnh nhân mãn tính'],
    benefits: ['Hỗ trợ nghiên cứu', 'BHYT'],
    contactEmail: 'hr@endocrine.vn',
  },
  {
    _id: 'job_028',
    id: 'job_028',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    title: 'Kỹ thuật viên Phẫu thuật',
    description: 'Hỗ trợ phẫu thuật, chuẩn bị dụng cụ và chăm sóc hậu phẫu.',
    status: JobStatus.OPEN,
    location: 'Bệnh viện Nhi Đồng 1, TP.HCM',
    company: 'Bệnh viện Nhi Đồng 1',
    salaryRange: [7000000, 14000000],
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 25),
    requirements: ['Trung cấp/Kỹ thuật viên phẫu thuật', 'Kỹ năng xử lý cấp cứu nhi'],
    benefits: ['BHYT/BHXH', 'Đào tạo nâng cao'],
    contactEmail: 'hr@child1.vn',
  },
  {
    _id: 'job_029',
    id: 'job_029',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    title: 'Nhân viên Hành chính nhân sự',
    description: 'Quản lý hồ sơ nhân sự, tuyển dụng và các công việc văn phòng bệnh viện.',
    status: JobStatus.OPEN,
    location: 'Bệnh viện Đa khoa tỉnh Bình Dương',
    company: 'Bệnh viện Đa khoa Bình Dương',
    salaryRange: [6000000, 12000000],
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 20),
    requirements: ['Tốt nghiệp chuyên ngành quản trị nhân sự hoặc tương đương', 'Kinh nghiệm tuyển dụng là lợi thế'],
    benefits: ['Chế độ BH', 'Lương ổn định'],
    contactEmail: 'hr@bduh.vn',
  },
  {
    _id: 'job_030',
    id: 'job_030',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    title: 'Bác sĩ Cột sống',
    description: 'Chẩn đoán và phẫu thuật các bệnh lý cột sống, điều trị bệnh nhân thoát vị đĩa đệm.',
    status: JobStatus.OPEN,
    location: 'Bệnh viện Chấn thương Chỉnh hình TP.HCM',
    company: 'Bệnh viện Chấn thương Chỉnh hình TP.HCM',
    salaryRange: [22000000, 60000000],
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 40),
    requirements: ['Chuyên khoa Cột sống/Chấn thương chỉnh hình', 'Kinh nghiệm phẫu thuật cột sống'],
    benefits: ['Hỗ trợ chuyển giao kỹ thuật', 'Chế độ lương theo hiệu suất'],
    contactEmail: 'spine@orthohcm.vn',
  },

  {
    _id: 'job_031',
    id: 'job_031',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    title: 'Bác sĩ Tai biến mạch máu não',
    description: 'Khám và điều trị bệnh nhân đột quỵ, phối hợp can thiệp và phục hồi chức năng.',
    status: JobStatus.OPEN,
    location: 'Bệnh viện Bạch Mai, Hà Nội',
    company: 'Bệnh viện Bạch Mai',
    salaryRange: [16000000, 42000000],
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 55),
    requirements: ['Chuyên ngành Thần kinh hoặc Can thiệp thần kinh', 'Kinh nghiệm làm việc với đột quỵ cấp'],
    benefits: ['Chế độ đào tạo và hợp tác quốc tế', 'BHYT/BHXH'],
    contactEmail: 'neuro@bachmai.vn',
  },
  {
    _id: 'job_032',
    id: 'job_032',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    title: 'Chuyên viên Công nghệ thông tin y tế',
    description: 'Quản trị hệ thống HIS, hỗ trợ triển khai phần mềm quản lý bệnh viện và bảo mật dữ liệu y tế.',
    status: JobStatus.OPEN,
    location: 'Bệnh viện Đại học Y Hà Nội',
    company: 'Đại học Y Hà Nội - Bệnh viện',
    salaryRange: [10000000, 25000000],
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 30),
    requirements: ['Kinh nghiệm quản trị hệ thống HIS/EMR', 'Hiểu biết về bảo mật dữ liệu y tế'],
    benefits: ['Làm việc cùng đội ngũ nghiên cứu', 'Hỗ trợ đào tạo chuyên sâu'],
    contactEmail: 'it@hmu.edu.vn',
  },
  {
    _id: 'job_033',
    id: 'job_033',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    title: 'Bác sĩ Dị ứng - Miễn dịch',
    description: 'Chẩn đoán và điều trị các bệnh dị ứng, hen suyễn và rối loạn miễn dịch.',
    status: JobStatus.OPEN,
    location: 'Bệnh viện Nhi Trung ương',
    company: 'Bệnh viện Nhi Trung ương',
    salaryRange: [12000000, 28000000],
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 60),
    requirements: ['Chuyên khoa Dị ứng - Miễn dịch', 'Kinh nghiệm làm việc với trẻ em'],
    benefits: ['Đào tạo liên tục', 'BHYT'],
    contactEmail: 'allergy@childcenter.vn',
  },
  {
    _id: 'job_034',
    id: 'job_034',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    title: 'Chuyên viên Marketing y tế',
    description: 'Xây dựng chiến dịch truyền thông, quản lý thương hiệu bệnh viện và nội dung y tế.',
    status: JobStatus.OPEN,
    location: 'Bệnh viện FV, TP.HCM',
    company: 'Bệnh viện FV',
    salaryRange: [12000000, 30000000],
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 20),
    requirements: ['Kinh nghiệm marketing y tế', 'Kỹ năng viết nội dung và quản lý chiến dịch'],
    benefits: ['Môi trường quốc tế', 'Thưởng theo hiệu quả'],
    contactEmail: 'marketing@fv.vn',
  },
  {
    _id: 'job_035',
    id: 'job_035',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    title: 'Bác sĩ Dinh dưỡng Nhi',
    description: 'Tư vấn dinh dưỡng cho trẻ em, làm việc với phụ huynh và đội ngũ điều dưỡng.',
    status: JobStatus.OPEN,
    location: 'Bệnh viện Nhi Đồng 2, TP.HCM',
    company: 'Bệnh viện Nhi Đồng 2',
    salaryRange: [9000000, 20000000],
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 35),
    requirements: ['Chuyên khoa Dinh dưỡng Nhi', 'Kinh nghiệm tư vấn dinh dưỡng nhi'],
    benefits: ['Hỗ trợ đào tạo', 'BHYT/BHXH'],
    contactEmail: 'nutrition@child2.vn',
  },
  {
    _id: 'job_036',
    id: 'job_036',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    title: 'Bác sĩ Gây mê nhi',
    description: 'Gây mê cho phẫu thuật nhi, quản lý chăm sóc hồi sức sau mổ.',
    status: JobStatus.OPEN,
    location: 'Bệnh viện Nhi Đồng 1, TP.HCM',
    company: 'Bệnh viện Nhi Đồng 1',
    salaryRange: [14000000, 35000000],
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 60),
    requirements: ['Chuyên khoa Gây mê nhi', 'Kinh nghiệm gây mê cho trẻ nhỏ'],
    benefits: ['Đào tạo chuyên sâu', 'BHYT'],
    contactEmail: 'anes@child1.vn',
  },
  {
    _id: 'job_037',
    id: 'job_037',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    title: 'Bác sĩ Nội tim mạch nhi',
    description: 'Khám và điều trị các bệnh tim bẩm sinh và tim mắc phải ở trẻ em.',
    status: JobStatus.OPEN,
    location: 'Bệnh viện Nhi Trung ương',
    company: 'Bệnh viện Nhi Trung ương',
    salaryRange: [15000000, 36000000],
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 45),
    requirements: ['Chuyên khoa Tim mạch nhi', 'Kinh nghiệm siêu âm tim nhi'],
    benefits: ['Hỗ trợ nghiên cứu', 'BHYT'],
    contactEmail: 'pediatriccardio@nhi.vn',
  },
  {
    _id: 'job_038',
    id: 'job_038',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    title: 'Bác sĩ Thần kinh nhi',
    description: 'Chẩn đoán và điều trị các bệnh thần kinh ở trẻ em, phối hợp phục hồi chức năng.',
    status: JobStatus.OPEN,
    location: 'Bệnh viện Nhi Đồng 2, TP.HCM',
    company: 'Bệnh viện Nhi Đồng 2',
    salaryRange: [13000000, 30000000],
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 30),
    requirements: ['Chuyên khoa Thần kinh nhi', 'Kinh nghiệm chẩn đoán rối loạn phát triển thần kinh'],
    benefits: ['Đào tạo liên tục', 'BHYT'],
    contactEmail: 'pedsneuro@child2.vn',
  },
  {
    _id: 'job_039',
    id: 'job_039',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    title: 'Kỹ thuật viên Siêu âm',
    description: 'Thực hiện siêu âm cho các khoa lâm sàng, bảo đảm chất lượng và lưu trữ hình ảnh.',
    status: JobStatus.OPEN,
    location: 'Bệnh viện Hữu Nghị Việt Đức, Hà Nội',
    company: 'Bệnh viện Hữu Nghị Việt Đức',
    salaryRange: [8000000, 17000000],
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 40),
    requirements: ['Kỹ thuật viên siêu âm', 'Kinh nghiệm siêu âm tim, bụng, sản'],
    benefits: ['Được đào tạo nâng cao', 'BHYT/BHXH'],
    contactEmail: 'ultrasound@vietduc.vn',
  },
  {
    _id: 'job_040',
    id: 'job_040',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    title: 'Bác sĩ Thẩm mỹ',
    description: 'Thực hiện thủ thuật thẩm mỹ, tư vấn và theo dõi bệnh nhân sau điều trị.',
    status: JobStatus.OPEN,
    location: 'Bệnh viện Thẩm mỹ JW, TP.HCM',
    company: 'Bệnh viện Thẩm mỹ JW',
    salaryRange: [15000000, 40000000],
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 25),
    requirements: ['Bác sĩ chuyên khoa thẩm mỹ', 'Kinh nghiệm phẫu thuật thẩm mỹ'],
    benefits: ['Môi trường chuyên nghiệp', 'Chia sẻ doanh thu dịch vụ'],
    contactEmail: 'cosmetic@jw.vn',
  },

  {
    _id: 'job_041',
    id: 'job_041',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    title: 'Bác sĩ Y học gia đình',
    description: 'Khám và quản lý bệnh nhân tại phòng khám đa khoa, tư vấn sức khỏe ban đầu.',
    status: JobStatus.OPEN,
    location: 'Phòng khám Đại học Y Hà Nội',
    company: 'Phòng khám ĐHY Hà Nội',
    salaryRange: [9000000, 22000000],
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 60),
    requirements: ['Chuyên khoa Y học gia đình', 'Kỹ năng giao tiếp tốt'],
    benefits: ['Hỗ trợ học thuật', 'BHYT'],
    contactEmail: 'family@hmuclinic.vn',
  },
  {
    _id: 'job_042',
    id: 'job_042',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    title: 'Bác sĩ Sức khỏe sinh sản',
    description: 'Tư vấn sức khỏe sinh sản, chăm sóc tiền sản và chăm sóc sau sinh.',
    status: JobStatus.OPEN,
    location: 'Bệnh viện Phụ sản Hà Nội',
    company: 'Bệnh viện Phụ sản Hà Nội',
    salaryRange: [10000000, 26000000],
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 40),
    requirements: ['Bác sĩ chuyên khoa Sản', 'Kinh nghiệm tư vấn tiền sản'],
    benefits: ['Chương trình đào tạo liên tục', 'BHYT'],
    contactEmail: 'recruit@obgyhanoi.vn',
  },
  {
    _id: 'job_043',
    id: 'job_043',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    title: 'Chuyên viên Tài chính - Kế toán bệnh viện',
    description: 'Quản lý tài chính, lập báo cáo, xử lý thanh toán bệnh nhân và quản trị chi phí.',
    status: JobStatus.OPEN,
    location: 'Bệnh viện Đại học Y Dược TP.HCM',
    company: 'Bệnh viện ĐHYD TP.HCM',
    salaryRange: [9000000, 22000000],
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 30),
    requirements: ['Kế toán/ Tài chính', 'Kinh nghiệm kế toán bệnh viện là lợi thế'],
    benefits: ['Chế độ lương theo năng lực', 'BH'],
    contactEmail: 'finance@hcmuh.vn',
  },
  {
    _id: 'job_044',
    id: 'job_044',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    title: 'Bác sĩ Y tế dự phòng',
    description: 'Tham gia giám sát dịch tễ, triển khai chương trình tiêm chủng và phòng chống dịch bệnh.',
    status: JobStatus.OPEN,
    location: 'Viện Vệ sinh Dịch tễ Trung ương',
    company: 'Viện Vệ sinh Dịch tễ TW',
    salaryRange: [10000000, 24000000],
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 50),
    requirements: ['Chuyên ngành Y tế dự phòng', 'Kinh nghiệm giám sát dịch tễ'],
    benefits: ['Chế độ công tác nghiên cứu', 'BHYT'],
    contactEmail: 'epid@nihe.vn',
  },
  {
    _id: 'job_045',
    id: 'job_045',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    title: 'Bác sĩ Sức khỏe lao động',
    description: 'Khám sức khỏe nghề nghiệp, tư vấn và quản lý chương trình sức khỏe lao động cho doanh nghiệp.',
    status: JobStatus.OPEN,
    location: 'Trung tâm Y tế dự phòng tỉnh Đồng Nai',
    company: 'Trung tâm Y tế Đồng Nai',
    salaryRange: [8000000, 18000000],
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 30),
    requirements: ['Bác sĩ chuyên ngành Sức khỏe nghề nghiệp', 'Kinh nghiệm khám sức khỏe doanh nghiệp'],
    benefits: ['Chế độ BH', 'Làm việc giờ hành chính'],
    contactEmail: 'occupational@dongnai.gov.vn',
  },
  {
    _id: 'job_046',
    id: 'job_046',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    title: 'Bác sĩ Siêu âm Sản - Nhi',
    description: 'Thực hiện siêu âm cho sản nhi, đọc hình ảnh và tư vấn trước sinh.',
    status: JobStatus.OPEN,
    location: 'Bệnh viện Phụ sản Trung ương, Hà Nội',
    company: 'Bệnh viện Phụ sản Trung ương',
    salaryRange: [13000000, 30000000],
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 60),
    requirements: ['Kinh nghiệm siêu âm sản - nhi', 'Chứng chỉ siêu âm nâng cao'],
    benefits: ['Hỗ trợ học thuật', 'BHYT'],
    contactEmail: 'obgyn@ps.tw.vn',
  },
  {
    _id: 'job_047',
    id: 'job_047',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    title: 'Bác sĩ Phẫu thuật Tim mạch',
    description: 'Phẫu thuật tim mở, thay van tim và điều trị bệnh tim bẩm sinh ở người lớn và trẻ em.',
    status: JobStatus.OPEN,
    location: 'Bệnh viện Tim mạch Quốc gia Việt Nam',
    company: 'Bệnh viện Tim mạch Quốc gia',
    salaryRange: [30000000, 90000000],
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 20),
    requirements: ['Phẫu thuật tim mạch chuyên sâu', 'Kinh nghiệm phẫu thuật tim mở'],
    benefits: ['Thưởng hiệu suất cao', 'Hợp tác quốc tế'],
    contactEmail: 'cardiosurgery@nationalheart.vn',
  },
  {
    _id: 'job_048',
    id: 'job_048',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    title: 'Bác sĩ Nội tổng quát (Khám bệnh)',
    description: 'Khám và điều trị các bệnh nội khoa thông thường, quản lý bệnh mãn tính tại phòng khám',
    status: JobStatus.OPEN,
    location: 'Phòng khám đa khoa tư nhân, Hà Nội',
    company: 'Phòng khám Sức khỏe ABC',
    salaryRange: [8000000, 20000000],
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 30),
    requirements: ['Bác sĩ Nội tổng quát', 'Kỹ năng khám bệnh và giao tiếp tốt'],
    benefits: ['Làm việc giờ hành chính', 'Thưởng doanh thu'],
    contactEmail: 'hr@abcclinic.vn',
  },
  {
    _id: 'job_049',
    id: 'job_049',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    title: 'Bác sĩ Gây mê hồi sức (ICU)',
    description: 'Quản lý gây mê và chăm sóc hồi sức cho bệnh nhân nặng trong ICU.',
    status: JobStatus.OPEN,
    location: 'Bệnh viện Trung ương Huế',
    company: 'Bệnh viện Trung ương Huế',
    salaryRange: [16000000, 42000000],
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 45),
    requirements: ['Chuyên khoa Gây mê hồi sức', 'Kinh nghiệm ICU'],
    benefits: ['Đào tạo chuyên sâu', 'BHYT/BHXH'],
    contactEmail: 'icu@huehosp.vn',
  },
  {
    _id: 'job_050',
    id: 'job_050',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    title: 'Bác sĩ Phòng khám COVID-19 & Nhiễm',
    description: 'Khám, chẩn đoán và điều trị các bệnh truyền nhiễm, tham gia chương trình kiểm soát nhiễm khuẩn.',
    status: JobStatus.OPEN,
    location: 'Bệnh viện Bệnh Nhiệt đới Trung ương',
    company: 'Bệnh viện Bệnh Nhiệt đới TW',
    salaryRange: [12000000, 30000000],
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 60),
    requirements: ['Chuyên khoa Truyền nhiễm', 'Kinh nghiệm kiểm soát nhiễm khuẩn'],
    benefits: ['Hỗ trợ nhiệm vụ cộng đồng', 'Chế độ BH'],
    contactEmail: 'infectious@nid.vn',
  },
];
