import type { Bulletin } from '@/models/Bulletin';

export const mockBulletins: Bulletin[] = [
  {
    _id: '1',
    id: '1',
    title: 'Thông báo về việc cập nhật chính sách bảo mật dữ liệu người dùng trên hệ thống diễn đàn y tế',
    slug: 'cap-nhat-chinh-sach-bao-mat-du-lieu-nguoi-dung',
    content: 'Nội dung thông báo về việc cập nhật chính sách bảo mật dữ liệu người dùng.',
    thumbnail: 'https://example.com/thumbnail1.jpg',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachment: [],
  },
  {
    _id: '2',
    id: '2',
    title: 'Hướng dẫn chi tiết cách sử dụng chức năng tìm kiếm nâng cao trên diễn đàn y tế trực tuyến',
    slug: 'huong-dan-su-dung-tim-kiem-nang-cao',
    content: 'Nội dung hướng dẫn sử dụng chức năng tìm kiếm nâng cao.',
    thumbnail: 'https://example.com/thumbnail2.jpg',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachment: [],
  },
  {
    _id: '3',
    id: '3',
    title: 'Thông báo về lịch bảo trì hệ thống diễn đàn và các lưu ý dành cho người dùng',
    slug: 'lich-bao-tri-he-thong-dien-dan',
    content: 'Nội dung thông báo về lịch bảo trì hệ thống.',
    thumbnail: 'https://example.com/thumbnail3.jpg',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachment: [],
  },
  {
    _id: '4',
    id: '4',
    title: 'Cập nhật mới nhất về các chuyên mục thảo luận dành cho bác sĩ và chuyên gia y tế',
    slug: 'cap-nhat-chuyen-muc-thao-luan-bac-si',
    content: 'Nội dung cập nhật về các chuyên mục thảo luận.',
    thumbnail: 'https://example.com/thumbnail4.jpg',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachment: [],
  },
  {
    _id: '5',
    id: '5',
    title: 'Thông báo về việc tổ chức hội thảo trực tuyến chuyên đề sức khỏe cộng đồng',
    slug: 'to-chuc-hoi-thao-truc-tuyen-suc-khoe',
    content: 'Nội dung thông báo về hội thảo trực tuyến.',
    thumbnail: 'https://example.com/thumbnail5.jpg',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachment: [],
  },
  {
    _id: '6',
    id: '6',
    title: 'Hướng dẫn đăng ký tài khoản và xác thực thông tin cá nhân trên diễn đàn',
    slug: 'huong-dan-dang-ky-tai-khoan-va-xac-thuc',
    content: 'Nội dung hướng dẫn đăng ký tài khoản.',
    thumbnail: 'https://example.com/thumbnail6.jpg',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachment: [],
  },
  {
    _id: '7',
    id: '7',
    title: 'Thông báo về việc nâng cấp giao diện người dùng và trải nghiệm mới trên diễn đàn',
    slug: 'nang-cap-giao-dien-nguoi-dung',
    content: 'Nội dung thông báo về việc nâng cấp giao diện.',
    thumbnail: 'https://example.com/thumbnail7.jpg',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachment: [],
  },
  {
    _id: '8',
    id: '8',
    title: 'Cảnh báo về các hành vi vi phạm quy định và hướng dẫn xử lý khi gặp sự cố',
    slug: 'canh-bao-vi-pham-quy-dinh',
    content: 'Nội dung cảnh báo về các hành vi vi phạm.',
    thumbnail: 'https://example.com/thumbnail8.jpg',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachment: [],
  },
  {
    _id: '9',
    id: '9',
    title: 'Thông báo về việc bổ sung chức năng đăng tải tài liệu tham khảo cho thành viên',
    slug: 'bo-sung-chuc-nang-dang-tai-tai-lieu',
    content: 'Nội dung thông báo về chức năng đăng tải tài liệu.',
    thumbnail: 'https://example.com/thumbnail9.jpg',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachment: [],
  },
  {
    _id: '10',
    id: '10',
    title: 'Hướng dẫn chi tiết về cách bảo mật tài khoản cá nhân trên diễn đàn y tế',
    slug: 'huong-dan-bao-mat-tai-khoan-ca-nhan',
    content: 'Nội dung hướng dẫn bảo mật tài khoản cá nhân.',
    thumbnail: 'https://example.com/thumbnail10.jpg',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachment: [],
  },
  {
    _id: '11',
    id: '11',
    title: 'Thông báo về việc cập nhật danh sách các chuyên gia tư vấn trực tuyến',
    slug: 'cap-nhat-danh-sach-chuyen-gia-tu-van',
    content: 'Nội dung thông báo về danh sách chuyên gia tư vấn.',
    thumbnail: 'https://example.com/thumbnail11.jpg',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachment: [],
  },
  {
    _id: '12',
    id: '12',
    title: 'Cập nhật các quy định mới về đăng bài và bình luận trên diễn đàn y tế',
    slug: 'cap-nhat-quy-dinh-dang-bai-binh-luan',
    content: 'Nội dung cập nhật quy định đăng bài và bình luận.',
    thumbnail: 'https://example.com/thumbnail12.jpg',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachment: [],
  },
  {
    _id: '13',
    id: '13',
    title: 'Thông báo về việc triển khai chương trình tri ân thành viên tích cực',
    slug: 'trien-khai-chuong-trinh-tri-an-thanh-vien',
    content: 'Nội dung thông báo về chương trình tri ân thành viên.',
    thumbnail: 'https://example.com/thumbnail13.jpg',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachment: [],
  },
  {
    _id: '14',
    id: '14',
    title: 'Hướng dẫn sử dụng chức năng nhắn tin riêng tư giữa các thành viên diễn đàn',
    slug: 'huong-dan-su-dung-nhan-tin-rieng-tu',
    content: 'Nội dung hướng dẫn sử dụng nhắn tin riêng tư.',
    thumbnail: 'https://example.com/thumbnail14.jpg',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachment: [],
  },
  {
    _id: '15',
    id: '15',
    title: 'Thông báo về việc hợp tác với các tổ chức y tế uy tín trong và ngoài nước',
    slug: 'hop-tac-voi-to-chuc-y-te-uy-tin',
    content: 'Nội dung thông báo về hợp tác với tổ chức y tế.',
    thumbnail: 'https://example.com/thumbnail15.jpg',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachment: [],
  },
  {
    _id: '16',
    id: '16',
    title: 'Cập nhật các tính năng mới hỗ trợ người dùng tra cứu thông tin y khoa nhanh chóng',
    slug: 'cap-nhat-tinh-nang-tra-cuu-thong-tin-y-khoa',
    content: 'Nội dung cập nhật tính năng tra cứu thông tin y khoa.',
    thumbnail: 'https://example.com/thumbnail16.jpg',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachment: [],
  },
  {
    _id: '17',
    id: '17',
    title: 'Thông báo về việc tổ chức cuộc thi viết bài chia sẻ kinh nghiệm chăm sóc sức khỏe',
    slug: 'to-chuc-cuoc-thi-viet-bai-chia-se-kinh-nghiem',
    content: 'Nội dung thông báo về cuộc thi viết bài.',
    thumbnail: 'https://example.com/thumbnail17.jpg',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachment: [],
  },
  {
    _id: '18',
    id: '18',
    title: 'Hướng dẫn sử dụng chức năng báo cáo bài viết vi phạm nội quy diễn đàn',
    slug: 'huong-dan-bao-cao-bai-viet-vi-pham',
    content: 'Nội dung hướng dẫn báo cáo bài viết vi phạm.',
    thumbnail: 'https://example.com/thumbnail18.jpg',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachment: [],
  },
  {
    _id: '19',
    id: '19',
    title: 'Thông báo về việc nâng cấp hệ thống bảo mật và phòng chống tấn công mạng',
    slug: 'nang-cap-he-thong-bao-mat-phong-chong-tan-cong',
    content: 'Nội dung thông báo về nâng cấp hệ thống bảo mật.',
    thumbnail: 'https://example.com/thumbnail19.jpg',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachment: [],
  },
  {
    _id: '20',
    id: '20',
    title: 'Cập nhật danh sách các chủ đề thảo luận nổi bật trong tháng trên diễn đàn y tế',
    slug: 'cap-nhat-chu-de-thao-luan-noi-bat-trong-thang',
    content: 'Nội dung cập nhật danh sách chủ đề thảo luận nổi bật.',
    thumbnail: 'https://example.com/thumbnail20.jpg',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachment: [],
  },
];
